stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "uiaam/swap-flask-app"
  IMAGE_TAG: "latest"
  DOCKER_DRIVER: overlay2   # pour Docker-in-Docker

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind   #  uniquement 1 service dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $IMAGE_NAME:$IMAGE_TAG swap-app
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl apply -f kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/service.yaml