stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2   # pour Docker-in-Docker

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t uiaam/swap-flask-app:latest swap-app
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push uiaam/swap-flask-app:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - export KUBECONFIG=/home/gitlab-runner/.kube/config
    - kubectl apply -f kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/service.yaml