apiVersion: v1
kind: Service
metadata:
  name: swap-flask-app-service
spec:
  type: NodePort
  selector:
    app: swap-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  